spring:
  batch:
    job:
      names: ${job.name:NONE}
      # 모든 잡이 실행되는 것을 막음. 실행 인자로 job.name을 넘겨주면 해당 잡만 실행됨.
    # 운영환경에서 배치 스키마를 자동으로 생성하지 않도록 설정
    jdbc:
      initialize-schema: never
  datasource:
    member:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://testdb.com:3306/dev_member?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
    batch:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://testdb.com:3306/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
      # bulk insert를 위한 설정 rewriteBatchedStatements=true
      username: root
      password: root
    eas:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://testdb-pg.com:5432/dev_eas
      username:
      password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true